#!Groovy

pipeline {

    agent any

    options { 
        checkoutToSubdirectory('mozart2')
    }

    stages {
        try {
        stage ('Generate sources') {
            steps {
                sh 'bash mozart2/ci/download_llvm.sh'

                dir('build') {
                    sh """
                        cmake "-DCMAKE_BUILD_TYPE=Release" \
                            "-DMOZART_BOOST_USE_STATIC_LIBS=False" \
                            "-DCMAKE_PROGRAM_PATH=$WORKSPACE/llvm-install/usr/bin" \
                            "-DCMAKE_PREFIX_PATH=$WORKSPACE/llvm-install/usr/lib/llvm-4.0/lib/cmake"
                            $WORKSPACE/mozart2
                    """
                    sh 'make dist VERBOSE=1 -j4'
                }

                archiveArtifacts 'build/mozart2-*-Source.zip'
            }
        }
}
            finally {
                always {
                    sh 'ls -1 | grep -v llvm-download | xargs rm -rf'
                }
            }

        stage ('Build') {
            steps {
                echo 'lol'
            }
        }
    }
}
